docker_front_end/web-app/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('ups/', include('myapp.urls')),
]


urlpatterns += [
    path('', RedirectView.as_view(url='/ups/', permanent=True)),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

docker_front_end/web-app/myapp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

urlpatterns = [
    path('', views.index, name='index'),
    path('packages/', views.PackageListView.as_view(), name='packages'),
    path('packages/<int:pk>', views.PackageDetailView.as_view(), name='package-detail'),
    path('packages/<int:pk>/update/', views.PackageUpdate.as_view(), name='package_update'),
    path('survey/create/', views.SurveyCreate.as_view(), name='survey_create'),


]

# User
urlpatterns += [

    path('signup/', views.register, name='signup'),
    path('profile', views.profile, name='profile'),
]

docker_front_end/web-app/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

PACKAGE_STATUS = (
    (0, 'Preparing for delivery'),
    (1, 'In transit'),
    (2, 'Delivered')
)

Truck_STATUS = (
    (1, 'idle'),
    (2, 'traveling'),
    (3, 'arrive warehouse'),
    (4, 'loading'),
    (5, 'loaded'),
    (6, 'delivering')
)


class truck(models.Model):
    truck_id = models.IntegerField()
    truck_status = models.SmallIntegerField(choices=Truck_STATUS, default=1)

    def __str__(self):
        return f'{self.truck_id},{self.truck_status}'


class package(models.Model):
    package_id = models.BigIntegerField()
    owner =models.CharField(max_length=50,blank=True,null=True)
    truckid = models.IntegerField(null=True)
    destination_x = models.IntegerField(null=True)
    destination_y = models.IntegerField(null=True)
    package_status = models.SmallIntegerField(choices=PACKAGE_STATUS, default=0)
    description = models.CharField(max_length=200,blank=True,null=True)

    def __str__(self):
        return f'{self.package_id},{self.destination_x},{self.destination_y}'

    def get_absolute_url(self):
        return reverse('package-detail', args=[str(self.id)])




class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Phone_number = models.CharField(max_length=30, verbose_name="Phone Number", blank=True)

    Address = models.CharField(
        max_length=50,
        verbose_name="Address",
        blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

class survey(models.Model):
    package_id = models.BigIntegerField()
    satisfied = models.CharField(max_length=1,blank=True,null=True)
    content = models.CharField(max_length=300,blank = True,null=True)

    def __str__(self):
        return f'{self.package_id},{self.satisfied}'

    def get_absolute_url(self):
        return reverse('index')

docker_front_end/web-app/myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2','first_name', 'last_name']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email','first_name','last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [  'Phone_number', 'Address']

docker_front_end/web-app/myapp/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from myapp.models import package, survey
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.core.mail import send_mail
from django.views.generic.edit import UpdateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages

from django.core.mail import send_mail


# Create your views here.
def index(request):
    package_list = package.objects.all()
    num_package = package_list.count()
    context = {
        'num_package': num_package,
    }
    query = request.GET.get("q")
    if query:
        packageid_list = package.objects.filter(package_id__icontains = query)
        num_package = packageid_list.count()


        if num_package is not 0:
            pack = package.objects.all().filter(package_id=query)

            dest_x = pack.values_list('destination_x')[0][0]
            dest_y = pack.values_list('destination_y')[0][0]
            status = pack.values_list('package_status')[0][0]
            context = {
                'package_id':query,

                'dest_x': dest_x,
                'dest_y': dest_y,
                'num_package': num_package,
                'status': status,
            }
    return render(request, 'index.html', context=context)


class PackageListView(LoginRequiredMixin, generic.ListView):
    model = package

    def get_queryset(self):
        return package.objects.filter(owner=self.request.user)

    paginate_by = 10

class PackageDetailView(LoginRequiredMixin,generic.DetailView):
    model = package

class PackageUpdate(LoginRequiredMixin,UpdateView):
    model = package
    fields = ['destination_x','destination_y']


class SurveyCreate(LoginRequiredMixin,CreateView):
    model = survey
    fields =['package_id','satisfied','content']
    initial = {'Arrival_Time': '05/01/2018 12:00'}

    def form_valid(self, form):

        return super().form_valid(form)

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            messages.success(request, f'Account created for {username}!')
            send_mail(
                'Register Success',
                'Your account has been created successfully.',
                'UPS',
                [email],
                fail_silently=False,
            )
            return redirect('login')

    else:
        form = UserRegisterForm()

    return render(request, 'registration/signup.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'registration/profile.html', context)

docker_front_end/web-app/myapp/templates/myapp/package_detail.html
{% extends "base_generic.html" %}

{% block content %}

  <p><strong>Package ID</strong>{{ package.package_id }}</p> <!-- author detail link not yet defined -->
  <p><strong>Destination</strong> ({{ package.destination_x }}, {{package.destination_y}})</p>
  <p><strong><a href="{% url 'package_update' package.id %}">Change Package Delivery Destination</a></strong></p>
  <p><strong>Package Status</strong> {{ package.get_package_status_display }}</p>
  <p><strong>Package Description</strong>{{ package.description }}</p>

  {% if package.package_status is 2 %}
<p><strong>Feel free to fill a survey </strong><a href="{% url 'survey_create' %}">Click Here</a></p>
    <p><strong><a href="{% url 'index' %}">Home Page</a></strong></p>
  {% else %}
    <p><strong><a href="{% url 'index' %}">Home Page</a></strong></p>
  {% endif %}
{% endblock %}

docker_front_end/web-app/myapp/templates/myapp/package_form.html
{% extends "base_generic.html" %}

{% block content %}

{% if  package.package_status is not 0 %}
    {% if package.package_status is 1 %}
    <p><strong>Unable to change Destination, package has been shipped.</strong></p>
    <th><strong><a href="{{ package.get_absolute_url }}">Go Back</a></strong></th>
    {% endif %}
    {% if package.package_status is 2 %}
    <p><strong>Unable to change Destination, package has been delivered.</strong></p>
    <th><strong><a href="{{ package.get_absolute_url }}">Go Back</a></strong></th>
    {% endif %}

  {% else %}
    <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Submit">
    </form>
  {% endif %}
{% endblock %}

docker_front_end/web-app/myapp/templates/myapp/package_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Package List</h1>
  {% if package_list %}

  <table class="table table-striped table-bordered">
    <tr>

      <th>Package ID</th>
      <th>Destination</th>
      <th>Package Status</th>

    </tr>
    {% for package in package_list %}
      <tr>
        <th><strong><a href="{{ package.get_absolute_url }}">{{ package.package_id }}</a></strong></th>
        <th>({{package.destination_x}}, {{package.destination_y}})</th>
        <th>{{ package.get_package_status_display}}</th>
      </tr>


    {% endfor %}

  {% else %}
    <p>There are no package.</p>
  {% endif %}



{% endblock %}

docker_front_end/web-app/myapp/templates/myapp/survey_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

docker_front_end/web-app/templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>UPS Page</title>

    <!-- Bootstrap core CSS -->
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


    <style>
        body, html {
                  height: 100%;
                  background-position: center;
                  background-repeat: repeat;
                   background-size: cover;
                  background-image: url("https://images.pexels.com/photos/311039/pexels-photo-311039.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260");
              }

              li{
                  margin-top: auto;
                  margin: 10px;
              }
        main{
            margin: 100px;
            padding: 100px;
        }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'index' %}">UPS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'index'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
         <a class="nav-link" href="{% url 'packages'%}">My Packages</a>
        </li>

        <li class="nav-item">
         <a class="nav-link" href="{% url 'logout'%}">Log Out</a>
        </li>
        </li>
         <li class="nav-item">
         <a class="nav-link">{{user.get_username}}</a>
        </li>
         <li class="nav-item">
         <a class="nav-link" href="{% url 'profile' %}">Profile</a>
        </li>
      {% else %}
         <li class="nav-item">
         <a class="nav-link" href="{% url 'login'%}">Log In</a>
         </li>
        <li class="nav-item">
         <a class="nav-link " href="{%url 'signup'%}">Sign Up</a>
        </li>
        {% endif %}


    </ul>
    <form class="form-inline my-2 my-lg-0">

    </form>
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">

    {% block content %}{% endblock %}
  </div>

</main><!-- /.container -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script></body>
</html>

docker_front_end/web-app/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>UPS APP</h1>
  <h3>Package Info</h3>


  <h4><strong>Number of Packages in total:</strong> {{ num_package }} </h4>


  <form method='GET' action=''>
    <input type='text' name='q' placeholder='Input Tracking Number' />
    <input type='submit' value='Search'>
  </form>



  {% if package_id is not None %}

    <h4>Package Information</h4>
    <h5>Package_id: {{package_id}}</h5>
    <h5>Destination: ({{dest_x}},{{dest_y}})</h5>
    {% if status is 0%}
        <h5>Package_status: Preparing for delivery</h5>
    {% endif%}
     {% if status is 1%}
        <h5>Package_status: In transit</h5>
    {% endif%}
    {% if status is 2%}
        <h5>Package_status: Delivered</h5>
    {% endif%}





  {% endif %}


{% endblock %}